devices([
  "iPhone 16 Pro Max"
])

languages([
  "ko",
  "en-US"
])

scheme("CadenceBeep")
project("./CadenceBeep.xcodeproj")

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
skip_open_summary(true)
override_status_bar(true)
